# Generated by Django 4.2.1 on 2023-05-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], max_length=50, verbose_name='Zone Type')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, verbose_name='State Name')),
                ('zonefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone', verbose_name='Zone Foreign Key')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50, verbose_name='State Name')),
                ('statefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.zone', verbose_name='Zone Foreign Key')),
            ],
        ),
    ]
