# Generated by Django 4.2.1 on 2023-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('operational_head', 'operational_head'), ('zonal_head', 'zonal_head'), ('state_coordinator', 'state_coordinator'), ('asset_monitoring_officer', 'area_monitoring_officer'), ('area_manager', 'area_manager'), ('warehouse_supervisor', 'warehouse_supervisor')], max_length=30, verbose_name='User Role'),
        ),
    ]
