# Generated by Django 4.2.1 on 2023-05-17 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='statefk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state', verbose_name='Zone Foreign Key'),
        ),
    ]
