# Generated by Django 4.2.1 on 2023-05-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_district_statefk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
    ]
