# Generated by Django 4.2.1 on 2023-05-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_zone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'permissions': [('read_obj', 'Read Obj'), ('read_all_obj', 'Read All Obj')]},
        ),
    ]
