# Generated by Django 4.2.1 on 2023-05-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="district",
            old_name="statefk",
            new_name="fk",
        ),
        migrations.RenameField(
            model_name="state",
            old_name="zonefk",
            new_name="fk",
        ),
        migrations.RenameField(
            model_name="state",
            old_name="state_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="warehouse",
            old_name="premise_fk",
            new_name="fk",
        ),
        migrations.RemoveField(
            model_name="district",
            name="district_name",
        ),
        migrations.RemoveField(
            model_name="premise",
            name="district_fk",
        ),
        migrations.AddField(
            model_name="district",
            name="name",
            field=models.CharField(default=1, max_length=50, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.district",
                        verbose_name="Foreign Key",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="premise",
            name="fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.cluster",
                verbose_name="Foreign Key",
            ),
            preserve_default=False,
        ),
    ]
